# Generated by Django 3.2.6 on 2021-08-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('problem_descritpion', models.CharField(max_length=1000)),
                ('support_date_time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
    ]
