# Generated by Django 3.2.6 on 2021-08-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbackform', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callbackform',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
