# Generated by Django 3.2.6 on 2021-08-24 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbackform', '0002_alter_callbackform_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackform',
            name='submitted_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
