# Generated by Django 3.2.6 on 2021-08-24 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbackform', '0004_auto_20210824_2033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Callback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('company', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('problem_descritpion', models.CharField(max_length=1000)),
                ('submitted_date_time', models.DateTimeField()),
                ('support_date_time', models.DateTimeField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('o', 'Outstanding'), ('a', 'Archived')], default='Not reviewed', max_length=1)),
            ],
        ),
        migrations.DeleteModel(
            name='CallbackForm',
        ),
    ]
