# Generated by Django 3.2.6 on 2021-08-24 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('callbackform', '0005_auto_20210824_2302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='callback',
            old_name='problem_descritpion',
            new_name='problem_description',
        ),
    ]
