# Generated by Django 3.2.6 on 2021-08-25 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbackform', '0006_rename_problem_descritpion_callback_problem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='submitted_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='callback',
            name='support_date_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
