# Generated by Django 3.2.6 on 2021-08-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callbackform', '0007_auto_20210825_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='callback',
            name='submitted_date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
